### ISSUE TITLE
Problem with using connections without first, last, etc.

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-relay-ruby#1]
So I have 2 entities, a Job and a Build:

```ruby
  JobType = GraphQL::ObjectType.define do
    name "Job"
    description "The job in a build pipeline"

    field :id, !types.ID, "The unique ID for this job" do
      resolve -> (object, arguments, context) do
        object.uuid
      end
    end
  end

  BuildType = GraphQL::ObjectType.define do
    name "Build"
    description "A build from a pipeline"

    field :id, !types.ID, "The unique ID for this build" do
      resolve -> (object, arguments, context) do
        object.uuid
      end
    end
    connection :jobs, GraphQL::Relay::RelationConnection.create_type(JobType) do
      resolve -> (object, arguments, context) {
        object.jobs
      }
    end
  end
```

And the following query:

```
export default Relay.createContainer(BuildShow, {
  fragments: {
    build: () => Relay.QL`
      fragment on Build {
        jobs {
          edges {
            node {
              id
            }
          }
        }
      }
    `,
  },
});
```

When I try and run this in the browser, I get the following error:

> Warning: Invariant Violation: RelayQueryWriter: Cannot write edges for connection `jobs` on record `client:47debb0b1` without `first`, `last`, or `find` argument.warning @ warning.js:45_markAsRejected @ RelayPendingQueryTracker.js:163tryCallOne @ core.js:37(anonymous function) @ core.js:103flush @ browser-raw.js:52

Weirdly enough if I change `connection :jobs` to `field :jobs`, export my schema file, change it back to `connection :jobs`, it works fine.

I only seem to get the error when:

```
+                {
+                  "name": "first",
+                  "description": "",
+                  "type": {
+                    "kind": "SCALAR",
+                    "name": "Int",
+                    "ofType": null
+                  },
+                  "defaultValue": null
+                },
+                {
+                  "name": "after",
+                  "description": "",
+                  "type": {
+                    "kind": "SCALAR",
+                    "name": "String",
+                    "ofType": null
+                  },
+                  "defaultValue": null
+                },
+                {
+                  "name": "last",
+                  "description": "",
+                  "type": {
+                    "kind": "SCALAR",
+                    "name": "Int",
+                    "ofType": null
+                  },
+                  "defaultValue": null
+                },
+                {
+                  "name": "before",
+                  "description": "",
+                  "type": {
+                    "kind": "SCALAR",
+                    "name": "String",
+                    "ofType": null
+                  },
+                  "defaultValue": null
+                },
+                {
+                  "name": "order",
+                  "description": "",
+                  "type": {
+                    "kind": "SCALAR",
+                    "name": "String",
+                    "ofType": null
+                  },
+                  "defaultValue": null
+                }
```

appears in my schema file. If I pass `first: 10` to the original jobs connection inside my query, then it all works as well.

**Comment by rmosolgo** [comment]
Woah, I think it might just be a requirement of Relay. 

I cloned the Relay repo and started up `examples/star-wars` locally. Then, I removed `first: 10` from here: 

https://github.com/facebook/relay/blob/master/examples/star-wars/js/components/StarWarsApp.js#L28

And I got the same error:

![image](https://cloud.githubusercontent.com/assets/2231765/9426381/c095b64a-48f1-11e5-89bf-2b7142b827fc.png)

So, it fails on graphql-js + relay, too :S I never _heard_ of required arguments there, but then again, I haven't gotten far on Relay yet!

**Comment by devknoll** [comment]
https://facebook.github.io/relay/graphql/connections.htm#sec-Arguments

**Comment by rmosolgo** [comment]
Ohh sure 'nuf, I see:

> ... must include

I initially understood that as "must accept" (ie, the _schema_ must include them), but I guess it means the _query_ must include them

**Comment by devknoll** [comment]
To me it also makes sense that the query must include them: a connection is for a potentially infinite stream of items, so you must ask for a particular range :smile:

**Comment by keithpitt** [comment]
Thanks for taking a look! I'll ask some of the relay crew to see if this behaviour is definitely intended and report back with my findings.

**Comment by rmosolgo** [comment]
any news on this?

**Comment by johanobergman** [comment]
I think this is a valid concern. For example, you might want to paginate a connection using a date range instead of "first" or "last".

**Comment by dylanahsmith** [comment]
If you have a small bounded has many association, then don't need pagination, so just return a list of associated object directly.

I think allowing unbounded queries on a relation that requires pagination is simply a denial of service vulnerability, which makes this library completely unsuitable for any application at scale.  Thus I think the bug here is that this usage is allowed on the server, when it really shouldn't be.

There are a number of bugs in RelationConnection that allow scanning across a large number of rows:
* There is no bounds checking on the `first` and `last` arguments to make sure they are within lower than some max limit
* [items.length is called on an unbounded relation](https://github.com/rmosolgo/graphql-relay-ruby/blob/88b3d94f75a6dd4c8b2604743108db31f66f8dcc/lib/graphql/relay/relation_connection.rb#L22)
* The result of [items.last(last)](https://github.com/rmosolgo/graphql-relay-ruby/blob/88b3d94f75a6dd4c8b2604743108db31f66f8dcc/lib/graphql/relay/relation_connection.rb#L22-L23) isn't assigned to `items`, so it ignores the `last` argument and returns an unbounded relation
* [has_next_page and has_previous_page](https://github.com/rmosolgo/graphql-relay-ruby/blob/88b3d94f75a6dd4c8b2604743108db31f66f8dcc/lib/graphql/relay/base_connection.rb#L79-L86) are implemented with unbounded count queries, which requires relational database to scan all those rows to count them.  Instead, add 1 to the limit, apply that limit in `sliced_nodes`, load the query, and trim the results to the actual limit in `paged_nodes`.

**Comment by rmosolgo** [comment]
Agreed that requiring first & last is the right move. Thanks for the heads up on those bugs! I'll take a look at those soon.

**Comment by rmosolgo** [comment]
I fixed a few of those & I took a try at fixing has-next / has-previous but I couldn't quite understand how that would work :(

**Comment by MisterRager** [comment]
For RelationConnection, it uses AR to count

**Comment by rmosolgo** [comment]
leaving out pagination arguments is supported by #37
