### ISSUE TITLE
Question: Ordering by id ascending

### ISSUE THREAD

**Issue by jwaldrip** [rmosolgo/graphql-relay-ruby#11]
How would I order by ID in ascending order?

**Comment by rmosolgo** [comment]
I think this is actually _outside_ the bounds of Relay compliance, but I added it because I wanted it. You can use the `order` argument and add a `-` to reverse the order. For example: https://github.com/rmosolgo/graphql-relay-ruby/blob/master/spec/graphql/relay/relation_connection_spec.rb#L79-L93

**Comment by jwaldrip** [comment]
Cool. Is is possible to do a custom order function on the type definition. It would be nice to specify a custom order function if need be.

**Comment by rmosolgo** [comment]
Sadly no :( 

You can see here that `RelationConnection` assumes you'll be ordering by a column: https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L38-L39

`ArrayConnection` sends the method to each item: https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/array_connection.rb#L32

So, if you were using an ArrayConnection, you could define the method on the objects themselves, but no way to do it in the schema definition yet! :cry: Definitely sounds like a good feature though.

**Comment by rmosolgo** [comment]
I removed the built-in "order" argument from the gem. Now, you should order your collection in the connection's `resolve` proc and return an ordered collection. This is better because "order" isn't part of the Relay spec and the built-in definition wasn't good enough and just got in the way!

You can see an example of custom ordering in the test fixtures: https://github.com/rmosolgo/graphql-relay-ruby/blob/master/spec/support/star_wars_schema.rb#L88-L97

Hope that helps!
